FROM node:14

COPY app.js .

# Generate self-signed SSL certificate
RUN openssl req -x509 -newkey rsa:4096 -keyout server.key -out server.crt -days 365 -nodes \
    -subj "/C=HR/ST=ZAGREB/L=ZAGREB/O=ReversingLabs/CN=rl-test.com"
EXPOSE 443

CMD node app.js
